# Generated by Django 3.2.8 on 2021-10-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postuid',
            new_name='postusername',
        ),
    ]
