# Generated by Django 3.2.8 on 2021-10-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211028_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
                ('mobileno', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
    ]
