# Generated by Django 3.2.8 on 2021-10-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='document',
            field=models.FileField(default=0, upload_to='docs/'),
            preserve_default=False,
        ),
    ]
